version: '3.8'

services:
  auth:
    build: .
    ports:
      - "127.0.0.1:3017:3000"
    environment:
      - RUST_BACKTRACE=1
      - BINDING_ADDRESS=127.0.0.1:3001
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///app/db.sqlite?mode=rwc}
      - JWT_SECRET=${JWT_SECRET}
      - POW_COMPLEXITY=${POW_COMPLEXITY:-19}
      - GAMERVII_COMPAT_ENABLED=${GAMERVII_COMPAT_ENABLED:-false}
      - GAMERVII_COMPAT_ENDPOINT=${GAMERVII_COMPAT_ENDPOINT}
      - GAMERVII_COMPAT_TOKEN=${GAMERVII_COMPAT_TOKEN}
    volumes:
      - ./db.sqlite:/app/db.sqlite
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"


networks:
  default:
    external: true
    name: my_shared_proxy_net
