use crate::app::http::ProblemDetails;
use crate::app::http::ProblemResponse;
use crate::domains::admin::discord as admin_discord;
use crate::domains::admin::email as admin_email;
use crate::domains::admin::handlers as admin_handlers;
use crate::domains::admin::referrals as admin_referrals;
use crate::domains::admin::service_tokens as admin_service_tokens;
use crate::domains::admin::squads as admin_squads;
use crate::domains::auth::handlers as auth_handlers;
use crate::domains::auth::polling as auth_polling;
use crate::domains::auth::verification as auth_verification;
use crate::domains::compat::gamervii as compat_gamervii;
use crate::domains::discord as discord_handlers;
use crate::domains::gunskins::handlers as gunskin_handlers;
use crate::domains::littlemice::handlers as littlemice_handlers;
use crate::domains::lootboxes::handlers as lootbox_handlers;
use crate::domains::meta::handlers as meta_handlers;
use crate::domains::ownership::handlers as ownership_handlers;
use crate::domains::referrals::handlers as referral_handlers;
use crate::domains::shop::handlers as shop_handlers;
use crate::domains::skins::handlers as skins_handlers;
use crate::domains::skins::types as skins_types;
use crate::domains::squads::handlers as squads_handlers;
use crate::domains::system::health as system_health;
use crate::domains::users::handlers;
use crate::services::lootboxes as lootbox_service;
use crate::services::ownership::catalog as ownership_catalog;
use crate::services::ownership::types as ownership_types;
use crate::services::shop as shop_service;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        admin_handlers::health,
        admin_handlers::me,
        admin_discord::send_notification,
        admin_email::send_test_receipt,
        admin_discord::create_broadcast,
        admin_discord::list_broadcasts,
        admin_discord::get_broadcast,
        admin_handlers::list_users,
        admin_handlers::get_user,
        admin_handlers::get_user_squad,
        admin_handlers::patch_user,
        admin_handlers::delete_user_skin,
        admin_handlers::deactivate_user,
        admin_handlers::activate_user,
        admin_handlers::reset_auth_epoch,
        admin_handlers::grant_superuser,
        admin_handlers::revoke_superuser,
        admin_handlers::get_user_restrictions,
        admin_handlers::grant_user_restriction,
        admin_handlers::revoke_user_restriction,
        admin_service_tokens::list_service_tokens,
        admin_service_tokens::create_service_token,
        admin_service_tokens::get_service_token,
        admin_service_tokens::get_service_token_audit,
        admin_service_tokens::rotate_service_token,
        admin_service_tokens::revoke_service_token,
        admin_referrals::list_campaigns,
        admin_referrals::create_campaign,
        admin_referrals::get_campaign,
        admin_referrals::patch_campaign,
        admin_referrals::revoke_campaign,
        admin_referrals::campaign_stats,
        admin_squads::list_squads,
        admin_squads::get_squad,
        admin_squads::patch_squad,
        admin_squads::restrict_squad,
        admin_squads::unrestrict_squad,
        admin_squads::delete_squad,
        admin_squads::kick_member,
        admin_squads::upload_squad_image,
        admin_squads::delete_squad_image,
        auth_handlers::prepare_auth,
        auth_handlers::authorize,
        auth_handlers::register,
        auth_polling::poll_auth_status,
        auth_verification::verify,
        handlers::get_me,
        handlers::search_users,
        handlers::update_nickname,
        handlers::get_my_restrictions,
        compat_gamervii::gamervii_auth,
        discord_handlers::list_events,
        gunskin_handlers::list_my_gunskin_selections,
        gunskin_handlers::get_my_gunskin_collection,
        gunskin_handlers::select_my_gunskin,
        gunskin_handlers::reset_my_gunskin,
        gunskin_handlers::get_user_selected_gunskin,
        gunskin_handlers::list_user_available_gunskins,
        gunskin_handlers::select_user_gunskin,
        gunskin_handlers::reset_user_gunskin,
        gunskin_handlers::list_admin_weapon_keys,
        meta_handlers::get_restrictions_meta,
        meta_handlers::get_squads_config,
        lootbox_handlers::list_public_lootboxes,
        lootbox_handlers::get_public_lootbox,
        lootbox_handlers::get_my_lootboxes,
        lootbox_handlers::get_my_lootbox_open_history,
        lootbox_handlers::open_my_lootbox,
        lootbox_handlers::list_admin_lootboxes,
        lootbox_handlers::create_lootbox,
        lootbox_handlers::get_admin_lootbox,
        lootbox_handlers::patch_lootbox,
        lootbox_handlers::create_lootbox_drop,
        lootbox_handlers::patch_lootbox_drop,
        lootbox_handlers::delete_lootbox_drop,
        lootbox_handlers::open_user_lootbox,
        lootbox_handlers::get_user_lootbox_open_history,
        lootbox_handlers::get_all_lootbox_open_history,
        littlemice_handlers::create_check,
        littlemice_handlers::push_check,
        littlemice_handlers::get_check_status,
        littlemice_handlers::fail_check,
        crate::domains::admin::littlemice::list_checks,
        crate::domains::admin::littlemice::list_checks_by_player,
        crate::domains::admin::littlemice::get_check,
        crate::domains::admin::littlemice::get_screenshot,
        crate::domains::admin::littlemice::get_screenshot2,
        crate::domains::admin::littlemice::get_log,
        ownership_handlers::list_public_assets,
        ownership_handlers::get_public_asset,
        ownership_handlers::get_public_asset_image,
        ownership_handlers::get_public_asset_model,
        ownership_handlers::get_public_asset_texture,
        ownership_handlers::list_admin_assets,
        ownership_handlers::get_admin_asset,
        ownership_handlers::get_admin_asset_image,
        ownership_handlers::get_admin_asset_model,
        ownership_handlers::get_admin_asset_texture,
        ownership_handlers::create_asset,
        ownership_handlers::patch_asset,
        ownership_handlers::upload_asset_image,
        ownership_handlers::delete_asset_image,
        ownership_handlers::get_my_inventory,
        ownership_handlers::check_my_inventory_presence,
        ownership_handlers::get_my_stackables,
        ownership_handlers::get_my_entitlements,
        ownership_handlers::get_my_active_expirables,
        ownership_handlers::get_my_subscription_status,
        ownership_handlers::get_my_wallet,
        ownership_handlers::get_my_default_wallet_balance,
        ownership_handlers::get_my_wallet_balance,
        ownership_handlers::get_my_wallet_transactions,
        ownership_handlers::get_user_inventory,
        ownership_handlers::get_user_subscription_status,
        ownership_handlers::get_user_inventory_history,
        ownership_handlers::grant_entitlement,
        ownership_handlers::revoke_entitlement,
        ownership_handlers::add_stackable,
        ownership_handlers::remove_stackable,
        ownership_handlers::set_stackable,
        ownership_handlers::prolong_expirable,
        ownership_handlers::prolong_plus_subscription,
        ownership_handlers::prolong_pro_subscription,
        ownership_handlers::set_expiration,
        ownership_handlers::revoke_expirable,
        ownership_handlers::get_user_default_wallet_balance,
        ownership_handlers::get_user_wallet_transactions,
        ownership_handlers::credit_default_wallet,
        ownership_handlers::debit_default_wallet,
        ownership_handlers::adjust_default_wallet_balance,
        ownership_handlers::credit_wallet,
        ownership_handlers::debit_wallet,
        ownership_handlers::adjust_wallet_balance,
        referral_handlers::get_referral,
        referral_handlers::my_referral_stats,
        shop_handlers::list_public_products,
        shop_handlers::get_public_product,
        shop_handlers::list_my_orders,
        shop_handlers::get_my_order,
        shop_handlers::get_my_order_receipt,
        shop_handlers::print_my_order_receipt,
        shop_handlers::create_my_order,
        shop_handlers::yookassa_webhook,
        shop_handlers::complete_my_mock_order,
        shop_handlers::list_admin_products,
        shop_handlers::list_admin_orders,
        shop_handlers::get_admin_product,
        shop_handlers::create_product,
        shop_handlers::patch_product,
        squads_handlers::create_squad,
        squads_handlers::find_squads_by_users,
        squads_handlers::get_squad,
        squads_handlers::get_squad_members,
        squads_handlers::get_squad_image,
        squads_handlers::patch_squad,
        squads_handlers::upload_squad_image,
        squads_handlers::delete_squad_image,
        squads_handlers::delete_squad,
        squads_handlers::leave_squad,
        squads_handlers::create_invite,
        squads_handlers::list_my_invites,
        squads_handlers::accept_invite,
        squads_handlers::decline_invite,
        squads_handlers::revoke_invite,
        squads_handlers::kick_member,
        squads_handlers::get_my_squad,
        skins_handlers::upload_my_skin,
        skins_handlers::get_default_skin,
        skins_handlers::get_skin,
        skins_handlers::get_default_skin_admin,
        skins_handlers::upload_default_skin_admin,
        system_health::health
    ),
    components(
        schemas(
            admin_handlers::AdminHealthResponse,
            admin_handlers::AdminMeResponse,
            admin_discord::SendDiscordNotificationRequest,
            admin_email::SendTestReceiptEmailRequest,
            admin_email::EmailDeliveryResponse,
            admin_discord::CreateDiscordBroadcastRequest,
            admin_discord::DiscordDeliveryResponse,
            admin_discord::DiscordBroadcastResponse,
            admin_handlers::AdminUserResponse,
            admin_handlers::AdminUsersListResponse,
            admin_handlers::PatchAdminUserRequest,
            admin_handlers::AdminUserSkinActionResponse,
            admin_handlers::DeactivateAdminUserRequest,
            admin_handlers::RestrictionReasonRequest,
            admin_handlers::AdminUserRestrictionResponse,
            crate::domains::admin::littlemice::LittlemiceCheckListItemResponse,
            crate::domains::admin::littlemice::LittlemiceCheckListResponse,
            crate::domains::admin::littlemice::LittlemiceCheckDetailResponse,
            admin_service_tokens::CreateServiceTokenRequest,
            admin_service_tokens::RotateServiceTokenRequest,
            admin_service_tokens::RevokeServiceTokenRequest,
            admin_service_tokens::ServiceTokenResponse,
            admin_service_tokens::ServiceTokenAuditResponse,
            admin_referrals::ListReferralCampaignsQuery,
            admin_referrals::ReferralCampaignStatsQuery,
            admin_squads::ListSquadsQuery,
            admin_squads::PatchAdminSquadRequest,
            admin_squads::ReasonRequest,
            admin_squads::AdminSquadResponse,
            admin_squads::AdminSquadListResponse,
            admin_squads::ActionResponse,
            auth_handlers::PrepareAuthResponse,
            auth_handlers::PrepareAuthRequest,
            auth_handlers::AuthorizeResponse,
            auth_handlers::AuthorizeRequest,
            auth_handlers::RegisterRequest,
            auth_polling::PollResponse,
            auth_verification::VerifyQuery,
            littlemice_handlers::CreateLittlemiceCheckRequest,
            littlemice_handlers::FailLittlemiceCheckRequest,
            littlemice_handlers::LittlemiceCreateCheckResponse,
            littlemice_handlers::LittlemiceCheckStatusResponse,
            littlemice_handlers::LittlemicePushAckResponse,
            auth_verification::VerifyResponse,
            handlers::UserResponse,
            handlers::UserSearchItemResponse,
            handlers::UserRestrictionResponse,
            handlers::UpdateNicknameRequest,
            compat_gamervii::GamerViiAuthRequest,
            compat_gamervii::GamerViiAuthResponse,
            discord_handlers::DiscordEventResponse,
            gunskin_handlers::SelectGunskinRequest,
            gunskin_handlers::GunskinAssetResponse,
            gunskin_handlers::SelectedGunskinResponse,
            gunskin_handlers::GunskinCollectionResponse,
            gunskin_handlers::GunskinSelectionListItemResponse,
            gunskin_handlers::WeaponKeyListResponse,
            meta_handlers::RestrictionMetaResponse,
            meta_handlers::RestrictionLocale,
            meta_handlers::RestrictionLocaleEntry,
            meta_handlers::SquadConfigResponse,
            lootbox_handlers::OpenLootboxQuery,
            lootbox_handlers::LootboxDefinitionResponse,
            lootbox_handlers::LootboxDropResponse,
            lootbox_handlers::LootboxDetailResponse,
            lootbox_handlers::OwnedLootboxResponse,
            lootbox_handlers::LootboxFeedEntryResponse,
            lootbox_handlers::LootboxRewardResponse,
            lootbox_handlers::LootboxOpenResultResponse,
            lootbox_handlers::LootboxOpenHistoryResponse,
            lootbox_service::CreateLootboxDefinitionInput,
            lootbox_service::UpdateLootboxDefinitionInput,
            lootbox_service::CreateLootboxDropInput,
            lootbox_service::UpdateLootboxDropInput,
            ownership_handlers::AssetListQuery,
            ownership_handlers::MutationBody,
            ownership_handlers::AssetResponse,
            ownership_handlers::AssetListResponse,
            ownership_handlers::StackableResponse,
            ownership_handlers::EntitlementResponse,
            ownership_handlers::ExpirableResponse,
            ownership_handlers::InventoryResponse,
            ownership_handlers::InventoryPresenceResponse,
            ownership_handlers::InventoryOperationResponse,
            ownership_handlers::WalletBalanceResponse,
            ownership_handlers::WalletTransactionResponse,
            ownership_handlers::SubscriptionStatusResponse,
            ownership_handlers::OkResponse,
            crate::services::referrals::CreateReferralCampaignInput,
            crate::services::referrals::UpdateReferralCampaignInput,
            crate::services::referrals::ReferralRewardInput,
            crate::services::referrals::ReferralRewardView,
            crate::services::referrals::ReferralCampaignView,
            crate::services::referrals::ReferralCampaignListResponse,
            crate::services::referrals::PublicReferralCampaignView,
            crate::services::referrals::ReferralStatsBucket,
            crate::services::referrals::ReferralStatsResponse,
            referral_handlers::ReferralStatsQuery,
            shop_handlers::ShopQuery,
            shop_handlers::AdminShopOrdersQuery,
            shop_handlers::ShopProductLocaleResponse,
            shop_handlers::ShopProductResponse,
            shop_handlers::ShopPaymentAttemptResponse,
            shop_handlers::ShopReceiptResponse,
            shop_handlers::ShopOrderResponse,
            shop_handlers::AdminShopOrderUserResponse,
            shop_handlers::AdminShopOrderResponse,
            shop_handlers::AdminShopOrdersListResponse,
            shop_handlers::ShopWebhookAckResponse,
            shop_handlers::YooKassaWebhookRequest,
            shop_handlers::YooKassaWebhookObjectRequest,
            ownership_catalog::CreateAssetDefinitionInput,
            ownership_catalog::UpdateAssetDefinitionInput,
            ownership_types::AssetKind,
            ownership_types::OwnershipModel,
            ownership_types::SkinRarity,
            shop_service::ProductLocaleInput,
            shop_service::CreateShopProductInput,
            shop_service::UpdateShopProductInput,
            shop_service::CreateShopOrderInput,
            ProblemDetails,
            ProblemResponse,
            squads_handlers::CreateSquadRequest,
            squads_handlers::FindSquadsByUsersRequest,
            squads_handlers::PatchSquadRequest,
            squads_handlers::CreateInviteRequest,
            squads_handlers::MatchedSquadUserResponse,
            squads_handlers::ServiceSquadLookupResponse,
            squads_handlers::SquadMemberResponse,
            squads_handlers::SquadResponse,
            squads_handlers::SquadInviteResponse,
            squads_handlers::SquadActionResponse,
            skins_handlers::DefaultSkinResponse,
            skins_types::ModelParam,
            skins_types::SkinModel,
            skins_types::UploadSkinResponse,
            system_health::HealthResponse
        )
    ),
    tags(
        (name = "admin", description = "Administrative API"),
        (name = "auth", description = "Authentication API"),
        (name = "compat", description = "Compatibility endpoints for legacy or external clients"),
        (name = "discord", description = "Public Discord integration endpoints"),
        (name = "gunskins", description = "Self-service gunskin selection API"),
        (name = "gunskins-system", description = "Service and administrative gunskin resolution API"),
        (name = "gunskins-admin", description = "Administrative gunskin metadata API"),
        (name = "debug", description = "Debug and test-only endpoints"),
        (name = "lootboxes", description = "Public and self-service lootbox catalog, ownership, and opening API"),
        (name = "lootboxes-admin", description = "Administrative lootbox configuration and investigation API"),
        (name = "littlemice", description = "Service anti-cheat verification API for creating checks, uploading snapshots, and reporting client-side failures"),
        (name = "ownership", description = "Public and self-service ownership catalog and inventory API"),
        (name = "ownership-admin", description = "Administrative inventory and asset catalog API"),
        (name = "referrals", description = "Referral campaign preview and creator analytics API"),
        (name = "referrals-admin", description = "Administrative referral campaign and registration statistics API"),
        (name = "meta", description = "Public metadata used by clients to drive UI and validation"),
        (name = "shop", description = "Public catalog and self-service purchase flow for shop products"),
        (name = "shop-admin", description = "Administrative shop product configuration API"),
        (name = "skins", description = "Skin upload and retrieval API"),
        (name = "squads", description = "Squad creation, membership, invite, and moderation API"),
        (name = "system", description = "Operational health endpoints"),
        (name = "users", description = "Authenticated user profile and self-service account endpoints"),
        (name = "wallet", description = "Self-service wallet API for currency balances and transactions"),
        (name = "wallet-admin", description = "Administrative wallet mutation and investigation API")
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

use utoipa::Modify;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.as_mut().unwrap(); // we can unwrap safely since we defined components in macro
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}
